# Generated by Django 6.0.5 on 2026-07-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(),
        ),
    ]
