# Generated by Django 6.0.3 on 2026-06-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song", models.CharField(max_length=225)),
                ("artist", models.CharField(max_length=225)),
                ("year", models.IntegerField()),
                ("album", models.CharField(max_length=225)),
            ],
        ),
    ]
